---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: example-validating-webhook
webhooks:
- name: webhook.example.com
  clientConfig:
    service:
      namespace: default
      name: example-webhook
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURvVENDQW9tZ0F3SUJBZ0lUTlFIV3liUkJEWTZmQ0FBTmVuU2E3bGhrN2pBTkJna3Foa2lHOXcwQkFRc0YKQURCcE1Rc3dDUVlEVlFRR0V3SlZVekVUTUJFR0ExVUVDQk1LUTJGc2FXWnZjbTVwWVRFV01CUUdBMVVFQnhNTgpVMkZ1SUVaeVlXNWphWE5qYnpFZk1CMEdBMVVFQ2hNV1NXNTBaWEp1WlhRZ1YybGtaMlYwY3l3Z1NXNWpMakVNCk1Bb0dBMVVFQ3hNRFYxZFhNQjRYRFRFNE1ESXlOekUxTURjd01Gb1hEVEl6TURJeU5qRTFNRGN3TUZvd2FURUwKTUFrR0ExVUVCaE1DVlZNeEV6QVJCZ05WQkFnVENrTmhiR2xtYjNKdWFXRXhGakFVQmdOVkJBY1REVk5oYmlCRwpjbUZ1WTJselkyOHhIekFkQmdOVkJBb1RGa2x1ZEdWeWJtVjBJRmRwWkdkbGRITXNJRWx1WXk0eEREQUtCZ05WCkJBc1RBMWRYVnpDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBTVhqRHB4cW5lWG8KeGpYZnQrN1ZDa2tLcWM3bG9zTFNka3RVMERJK0ZrQjk5S253L2xwVFVFbURpY2czY0UyRm40aFpHcnl3WitodgpabGQ1Q3BkVEl4TEE3NkcyazkrdjRsc2Urcm9tbjNjbjgvRmRvcnc5L1ZBQnVWRWpzN2RVNk1TQ2lXSC9BZDBUCllKSHllcXptbXFiTkxIWG5zT0h2Wkp2Szg0MFFJekVSNmNzMnVyYlhaK05pblc0bHJjdWJCZ3RXeW1xcU5LR3AKaHRGN3hRTVc0U1lzZklHK1FxYWQ4V21VczBMVURxT2VVMmlpVy83aEVXV3MybnRGREp2ZnYzc2E3bTZGOHU1aQoxV0g0ajNEV29LMjIrUzdpdStZbWFDZUtSQm5EZnNVSFdzM0xXbHVFRldyWWx4clBZMDFKeTlxWHYrZ1pRWFFnClFVS1M4WFc5QmxzQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0VHTUE4R0ExVWRFd0VCL3dRRk1BTUIKQWY4d0hRWURWUjBPQkJZRUZOYVNScXZzT2E5OHFSbFU3bHZJSzlmRW0yVXdNQTBHQ1NxR1NJYjNEUUVCQ3dVQQpBNElCQVFDUXN5QWlPUE5BOERPT0ZnWDdUZVZuSjFjNUlaZWx2TmtnWUIzVXFVK1p2bXFpUDhBK1NrZXJjbXNNCkNTWEJpOUJCQzZGakdHN3ptcXN1ZE9xdmpEazJVU0IwZXQ0WXlydmk0YWNWZlZEZXRQZHVuemh3c3dyWElQLysKajV4U2VUbUIzOGhEMGNaVHlHb1VrR3RhMXZYSHlUMitIN01UQ0ZiM2xkZEFmb2pjZHM4UTFqV2NjaFF6K25tYgpIeENyY3ZiaHNiU0NMRUFpYnU3eXRxOHhpK3g2R2RWTlB6cWV2OXlEK1J4RUNVbmE2bUREOGdmcmlYbUh2UnV0CkRhSEZqTHFLZVU1azB5M0tYS2U5cnFienBUVVJsTEE4R3RoY0Ywd3Vvd20wcEN4RHhleTNXaTdOaSs2LzJMQzgKYmZzd3JxUlo3aE9WVjRuZVZLaFBZdmFRaDBVcgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
  failurePolicy: Fail

